### ISSUE TITLE
Error con las películas

### ISSUE THREAD

**Issue by CarlosRubioTNM** [CarlosRubioTNM/fs1a-ad23#2]
Esas películas no me gustaron >:(

**Comment by CarlosRubioTNM** [comment]
No me importa

**Comment by CarlosRubioTNM** [comment]
Andale pues.

**Comment by CarlosRubioTNM** [comment]
¿Algo más para el rey?

**Comment by jondumen** [comment]
Le falta UwU a su pagina

**Comment by jondumen** [comment]
Nunca me respondio profe :(
![Yunjin 3](https://github.com/CarlosRubioTNM/fs1a-ad23/assets/84062001/a67fecf6-4105-4fa5-ada6-e956006df96b)
